
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Add_Material extends javax.swing.JFrame {

    
    dbhelper db=new dbhelper();
    /**
     * Creates new form Add_Material
     */
    public Add_Material() {
        initComponents();
        CustAutoIncerment();
        cmbItem_Type.setEditable(true);
        cmbItem_Type.setEnabled(true);
        cmbItem_Name.setEditable(true);
        cmbItem_Name.setEnabled(true);
        db.getTable(jTable1, "select * from add_material");
         db.FillCombo(cmbItem_Type, "select distinct(Item_Type) from add_material", "Item_Type");
        
    }
    
     public void Validate()
    {
        if(txtID.getText().equals("")||txtPrice.getText().equals("")||txtQuantity.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
        }
    }
     
     public void clearText()
     {
         txtID.setText("");
         txtPrice.setText("");
         txtQuantity.setText("");
         
     }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblid = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblItemType1 = new javax.swing.JLabel();
        lblItemName1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblQuantity1 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        cmbItem_Type = new javax.swing.JComboBox();
        cmbItem_Name = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Material");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 870, 110));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblid.setText("ID");
        jPanel3.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, 30));

        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrice.setText("Price");
        jPanel3.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel3.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, 30));

        lblItemType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblItemType1.setText("Item_Type");
        jPanel3.add(lblItemType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblItemName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblItemName1.setText("Item_Name");
        jPanel3.add(lblItemName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel3.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, 30));

        lblQuantity1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuantity1.setText("Quantity");
        jPanel3.add(lblQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel3.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        cmbItem_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItem_TypeActionPerformed(evt);
            }
        });
        jPanel3.add(cmbItem_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 30));

        jPanel3.add(cmbItem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 410, 370));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item_Type", "Item_Name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 110));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 420, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        CustAutoIncerment();
         validate();
         
         db.InsertData("insert into add_material(ID,Item_Type,Item_Name,Quantity,Price)values('"+txtID.getText()+"','"+cmbItem_Type.getSelectedItem().toString()+"','"+cmbItem_Name.getSelectedItem().toString()+"','"+txtQuantity.getText()+"','"+txtPrice.getText()+"')");
        db.getTable(jTable1, "select * from add_material");
         clearText();
          CustAutoIncerment();
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

     private void cmbItem_TypePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {                                                          
    db.FillCombo(cmbItem_Name, "select distinct(Item_Name) from add_material where Item_Type='"+cmbItem_Type.getSelectedItem().toString()+"'", "Item_Name");
    }  
    
    
    
    
    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void cmbItem_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItem_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItem_TypeActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
     
        db.updateRecord("update add_material set Price='"+txtPrice.getText()+"' where  Item_Type='"+cmbItem_Type.getSelectedItem().toString()+"'");
         db.getTable(jTable1, "select * from add_material");
         clearText();
          CustAutoIncerment();
    }//GEN-LAST:event_btnupdateActionPerformed

    
    
    public void CustAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from add_material";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtID.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Material().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox cmbItem_Name;
    private javax.swing.JComboBox cmbItem_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblItemName1;
    private javax.swing.JLabel lblItemType1;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
