
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Add_Food extends javax.swing.JFrame {
    
    dbhelper db=new dbhelper();

    /**
     * Creates new form Add_Food
     */
    public Add_Food() {
        initComponents();
        CustAutoIncerment();
        cmbItem_Type.setEditable(true);
        cmbItem_Type.setEnabled(true);
        cmbItem_Name.setEditable(true);
        cmbItem_Name.setEnabled(true);
        db.getTable(jTable1, "select * from add_food");
        db.FillCombo(cmbItem_Type, "select distinct(Item_Type) from add_food", "Item_Type");
    }
    
     public void Validate()
    {
        if(txtId.getText().equals("")||txtPrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
    }
     
      public void clearText()
     {
         txtId.setText("");
         txtPrice.setText("");
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblItem_Type = new javax.swing.JLabel();
        lblItem_Name = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        cmbItem_Type = new javax.swing.JComboBox();
        cmbItem_Name = new javax.swing.JComboBox();
        txtId = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblAddFood = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblId.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblId.setText("ID");
        jPanel2.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 110, 30));

        lblItem_Type.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblItem_Type.setText("Item_Type");
        jPanel2.add(lblItem_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));

        lblItem_Name.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblItem_Name.setText("Item_Name");
        jPanel2.add(lblItem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        lblPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblPrice.setText("Price");
        jPanel2.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        cmbItem_Type.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbItem_TypePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel2.add(cmbItem_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 110, 30));

        jPanel2.add(cmbItem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, 30));
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, 30));

        btnClear.setText("CLEAR");
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jPanel2.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 290));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddFood.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblAddFood.setText("Add Food Items");
        jPanel3.add(lblAddFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 400, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 70));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item_Type", "Item_Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 190));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 400, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        CustAutoIncerment();
        Validate();
        
         db.InsertData("insert into add_food(ID,Item_Type,Item_Name,Price)values('"+txtId.getText()+"','"+cmbItem_Type.getSelectedItem().toString()+"','"+cmbItem_Name.getSelectedItem().toString()+"','"+txtPrice.getText()+"')");
         db.getTable(jTable1, "select * from add_food");
        clearText();
          CustAutoIncerment();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbItem_TypePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbItem_TypePopupMenuWillBecomeInvisible
    db.FillCombo(cmbItem_Name, "select distinct(Item_Name) from add_food where Item_Type='"+cmbItem_Type.getSelectedItem().toString()+"'", "Item_Name");
    }//GEN-LAST:event_cmbItem_TypePopupMenuWillBecomeInvisible

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      db.updateRecord("update add_food set Price='"+txtPrice.getText()+"' where  Item_Type='"+cmbItem_Type.getSelectedItem().toString()+"'" );
      db.getTable(jTable1, "select * from add_food");
        clearText();
          CustAutoIncerment();
    }//GEN-LAST:event_btnUpdateActionPerformed

public void CustAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from add_food";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtId.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbItem_Name;
    private javax.swing.JComboBox cmbItem_Type;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddFood;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblItem_Name;
    private javax.swing.JLabel lblItem_Type;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
