
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Breakage extends javax.swing.JFrame {
    
     dbhelper db=new dbhelper();

    /**
     * Creates new form Bill
     */
    public Breakage() {
        initComponents();
        CustAutoIncerment();
        cmbItem_Name.setEditable(true);
        cmbItem_Type.setEnabled(true);
        cmbItem_Name.setEditable(true);
        cmbItem_Type.setEditable(true);
        db.getTable(jTable1, "select * from breakage");
        db.FillCombo(cmbItem_Name, "select distinct(Item_Name) from breakage", "Item_Name");
        db.FillCombo(cmbItem_Type, "select distinct(Item_Type) from breakage","Item_Type" );
    }
    
     public void Validate()
    {
        if(txtId.getText().equals("")||txtPrice.getText().equals("")||txtBrkquantity.getText().equals("")||txtPrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
        }
    }
     
     public void clearText()
     {
         txtId.setText("");
         txtPrice.setText("");
         txtBrkprice.setText("");
         txtBrkquantity.setText("");
     }
     
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBreakage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBrkprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbItem_Type = new javax.swing.JComboBox();
        cmbItem_Name = new javax.swing.JComboBox();
        txtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtBrkquantity = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 11, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBreakage.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblBreakage.setText("Breakage");
        jPanel3.add(lblBreakage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 250, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 80));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel4.setText("ID");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        txtBrkprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBrkpriceFocusLost(evt);
            }
        });
        txtBrkprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrkpriceActionPerformed(evt);
            }
        });
        jPanel4.add(txtBrkprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel5.setText("Item_Type");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel6.setText("Item_Name");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel7.setText("Brk.Price");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 30));

        cmbItem_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItem_TypeActionPerformed(evt);
            }
        });
        jPanel4.add(cmbItem_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 100, 30));

        jPanel4.add(cmbItem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, 30));
        jPanel4.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel8.setText("Price");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel9.setText("Brk.Quantity");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 30));
        jPanel4.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 30));
        jPanel4.add(txtBrkquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 100, 30));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 70, 30));

        btnCancle.setText("CANCLE");
        jPanel4.add(btnCancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 80, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 330, 370));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item_Type", "Item_Name", "Price", "Brk.Quantity", "Brk.Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 110));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 470, 370));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        CustAutoIncerment();
        validate();
        
        db.InsertData("insert into breakage(ID,Item_Type,Item_Name,Price,Brk_Quantity,Brk_Price)values('"+txtId.getText()+"','"+cmbItem_Type.getSelectedItem().toString()+"','"+cmbItem_Name.getSelectedItem().toString()+"','"+txtPrice.getText()+"','"+txtBrkquantity.getText()+"','"+txtBrkprice.getText()+"')");
         db.getTable(jTable1, "select * from breakage");
         clearText();
          CustAutoIncerment();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbItem_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItem_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItem_TypeActionPerformed

    private void txtBrkpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrkpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrkpriceActionPerformed

    private void txtBrkpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBrkpriceFocusLost
         cal();// TODO add your handling code here:
    }//GEN-LAST:event_txtBrkpriceFocusLost

    public void CustAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from breakage";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtId.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    public void cal()
      {
          double quantity,rate,amt;
          rate=Double.parseDouble(txtPrice.getText());
          quantity=Double.parseDouble(txtBrkquantity.getText());
          
          amt=quantity*rate;
          txtBrkprice.setText(String.valueOf(amt));
      }
    
            
      
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Breakage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Breakage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Breakage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Breakage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Breakage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbItem_Name;
    private javax.swing.JComboBox cmbItem_Type;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBreakage;
    private javax.swing.JTextField txtBrkprice;
    private javax.swing.JTextField txtBrkquantity;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
