
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Foodbilling extends javax.swing.JFrame {
 dbhelper db=new dbhelper();
    String MasterId,DetailIdl,CustId;
    
    /**
     * Creates new form Foodbilling
     */
    public Foodbilling() {
        initComponents();
        cmbItem_Name.setEditable(true);
        cmbItem_Type.setEditable(true);
        db.FillCombo(cmbItem_Name, "select distinct(Item_Name) from add_food", "Item_Name");
        db.FillCombo(cmbItem_Type, "select distinct(Item_Type) from add_food", "Item_Type");
        DetailsAutoIncerment();
        MasterAutoIncerment();
        CustAutoIncerment();
        
    }
    
     public void Validate()
    {
        if(txtname.getText().equals("")||txtaddress.getText().equals("")||txtmobmo.getText().equals("")||txtPrice.getText().equals("")||txtQuantity.getText().equals("")||txtNetamount.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
        }
    }
     
      public void clearText()
     {
         txtname.setText("");
         txtaddress.setText("");
         txtmobmo.setText("");
         txtPrice.setText("");
         txtQuantity.setText("");
         txtNetamount.setText("");
     }
      
    public void DetailsAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from food_details";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
          DetailIdl=(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }    
      public void addDataToTable()
    {
     DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
      model.addRow(new Object[]{lblProductId.getText(),cmbItem_Name.getSelectedItem().toString(),cmbItem_Type.getSelectedItem().toString(),txtPrice.getText().toString(),txtQuantity.getText(),txtNetamount.getText()});
      
      double sum=0;
        
        for(int i=0;i<jTable1.getRowCount();i++)
        {
           sum= sum+Double.parseDouble( jTable1.getValueAt(i,5).toString());
        }
        txttotamt.setText(String.valueOf(sum));
    }
    
      
public void MasterAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from food_master";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
            
        {
           i=db.rs.getInt(1);
        } 
          MasterId=(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }   

public void CustAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from customer";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
         CustId=(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }

 public void cal()
      {
          double quantity,rate,amt;
          rate=Double.parseDouble(txtPrice.getText());
          quantity=Double.parseDouble(txtQuantity.getText());
          
          amt=quantity*rate;
          txtNetamount.setText(String.valueOf(amt));
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblFoodbilling = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        lblmobno = new javax.swing.JLabel();
        txtmobmo = new javax.swing.JTextField();
        lblItem_Type = new javax.swing.JLabel();
        lblItem_Name = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbItem_Name = new javax.swing.JComboBox();
        cmbItem_Type = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtNetamount = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFinal_Amount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttotamt = new javax.swing.JTextField();
        txtdiscount = new javax.swing.JTextField();
        lblFinal_Amount = new javax.swing.JLabel();
        lblProductId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoodbilling.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblFoodbilling.setText("Food Billing");
        jPanel3.add(lblFoodbilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 330, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 90));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblname.setText("Customer_Name");
        jPanel5.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel5.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 30));

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setText("Address");
        jPanel5.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));
        jPanel5.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 110, 30));

        lblmobno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmobno.setText("Mobile No.");
        jPanel5.add(lblmobno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        jPanel5.add(txtmobmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, 30));

        lblItem_Type.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblItem_Type.setText("Item_Type");
        jPanel5.add(lblItem_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 100, 30));

        lblItem_Name.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblItem_Name.setText("Item_Name");
        jPanel5.add(lblItem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, 30));

        lblPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblPrice.setText("Price");
        jPanel5.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel11.setText("Net_Amount");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 100, 30));

        jPanel5.add(cmbItem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        jPanel5.add(cmbItem_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, 30));
        jPanel5.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, 30));
        jPanel5.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 100, 30));
        jPanel5.add(txtNetamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 100, 30));

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel5.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 70, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_id", "Item_Name", "Item_type", "Price", "Quantity", "Net_Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 810, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Total_Amount");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        txtFinal_Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinal_AmountActionPerformed(evt);
            }
        });
        jPanel5.add(txtFinal_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Discount");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));

        txttotamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotamtActionPerformed(evt);
            }
        });
        jPanel5.add(txttotamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 90, 30));

        txtdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiscountActionPerformed(evt);
            }
        });
        jPanel5.add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 90, 30));

        lblFinal_Amount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFinal_Amount.setText("Final_Amount");
        jPanel5.add(lblFinal_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        lblProductId.setText("id");
        jPanel5.add(lblProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 850, 540));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtFinal_AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinal_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinal_AmountActionPerformed

    private void txttotamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotamtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotamtActionPerformed

    private void txtdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiscountActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
            double price,qty,netAmt;
           price=Double.parseDouble(txtPrice.getText().toString());
           qty=Double.parseDouble(txtQuantity.getText().toString());
         //  netAmt=Double.parseDouble(txtNetamount.getText().toString());
            netAmt=price*qty;
            txtNetamount.setText(String.valueOf(netAmt));
addDataToTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foodbilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foodbilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foodbilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foodbilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foodbilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JComboBox cmbItem_Name;
    private javax.swing.JComboBox cmbItem_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblFinal_Amount;
    private javax.swing.JLabel lblFoodbilling;
    private javax.swing.JLabel lblItem_Name;
    private javax.swing.JLabel lblItem_Type;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblmobno;
    private javax.swing.JLabel lblname;
    private javax.swing.JTextField txtFinal_Amount;
    private javax.swing.JTextField txtNetamount;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtmobmo;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttotamt;
    // End of variables declaration//GEN-END:variables
}
