
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Material extends javax.swing.JFrame {

    /**
     * Creates new form Material
     */
    public Material() {
        initComponents();
    }
    
     public void Validate()
    {
        if(txtname.getText().equals("")||txtaddress.getText().equals("")||txtmobmo.getText().equals("")||txtPrice.getText().equals("")||txtQuantity.getText().equals("")||txtNetamount.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
        }
    }
     
      public void clearText()
     {
         txtname.setText("");
         txtaddress.setText("");
         txtmobmo.setText("");
         txtPrice.setText("");
         txtQuantity.setText("");
         txtNetamount.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        lblmobno = new javax.swing.JLabel();
        txtmobmo = new javax.swing.JTextField();
        lblItem_Type = new javax.swing.JLabel();
        lblItem_Name = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbItem_Name = new javax.swing.JComboBox();
        cmbItem_Type = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtNetamount = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Material Billing");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 90));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblname.setText("Customer_Name");
        jPanel3.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel3.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Address");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));
        jPanel3.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 110, 30));

        lblmobno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmobno.setText("Mobile No.");
        jPanel3.add(lblmobno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        jPanel3.add(txtmobmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, 30));

        lblItem_Type.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblItem_Type.setText("Item_Type");
        jPanel3.add(lblItem_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 100, 30));

        lblItem_Name.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblItem_Name.setText("Item_Name");
        jPanel3.add(lblItem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, 30));

        lblPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        lblPrice.setText("Price");
        jPanel3.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel11.setText("Net_Amount");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 100, 30));

        cmbItem_Name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbItem_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItem_NameActionPerformed(evt);
            }
        });
        jPanel3.add(cmbItem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        cmbItem_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cmbItem_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, 30));
        jPanel3.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, 30));
        jPanel3.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 100, 30));
        jPanel3.add(txtNetamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 100, 30));

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel3.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 70, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company_Name", "Address", "Mobile_no", "Item_id", "Item_Name", "Item_type", "Price", "Net_Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 260, 810, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 850, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void cmbItem_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItem_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItem_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Material().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JComboBox cmbItem_Name;
    private javax.swing.JComboBox cmbItem_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblItem_Name;
    private javax.swing.JLabel lblItem_Type;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblmobno;
    private javax.swing.JLabel lblname;
    private javax.swing.JTextField txtNetamount;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtmobmo;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
