
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Report_Option extends javax.swing.JFrame {
    
    dbhelper db=new dbhelper();
     String m_where;
    String m_report_source = "/Catering_System/";
    String m_sql_stmt;
    Map parametersMap = new HashMap();  

    /**
     * Creates new form Report_Option
     */
    public Report_Option() {
        initComponents();
    }
    
      public void Show()
    {
         try {
            DBUtilities dbUtilities = new DBUtilities();
            InputStream is = getClass().getResourceAsStream(m_report_source);

            JRDesignQuery jrDesignQuery = new JRDesignQuery();
            jrDesignQuery.setText(m_sql_stmt);

            JasperDesign jasperDesign = JRXmlLoader.load(is);
            jasperDesign.setQuery(jrDesignQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametersMap, dbUtilities.getConnection());
            JasperViewer.viewReport(jasperPrint, false);

        } catch (SQLException | JRException e) {
            System.out.println("Exception message " + e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAddFood = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAddMaterial = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblBreakage = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblCustomer = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblFoodBill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddFood.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddFood.setForeground(new java.awt.Color(51, 0, 51));
        lblAddFood.setText("Add Food Report");
        lblAddFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddFoodMouseClicked(evt);
            }
        });
        jPanel2.add(lblAddFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddMaterial.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddMaterial.setForeground(new java.awt.Color(51, 0, 51));
        lblAddMaterial.setText("Add Matetial Report");
        lblAddMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMaterialMouseClicked(evt);
            }
        });
        jPanel3.add(lblAddMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 280, 70));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBreakage.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblBreakage.setForeground(new java.awt.Color(51, 0, 51));
        lblBreakage.setText("Breakage Report");
        lblBreakage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBreakageMouseClicked(evt);
            }
        });
        jPanel4.add(lblBreakage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 280, 70));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomer.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(51, 0, 51));
        lblCustomer.setText("Customer Report");
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerMouseClicked(evt);
            }
        });
        jPanel5.add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 280, 70));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoodBill.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblFoodBill.setForeground(new java.awt.Color(51, 0, 51));
        lblFoodBill.setText("Food Bill Report");
        lblFoodBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoodBillMouseClicked(evt);
            }
        });
        jPanel6.add(lblFoodBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 280, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddFoodMouseClicked
         m_report_source = "rptFood.jrxml";
        m_sql_stmt = "SELECT add_food.`ID` AS add_food_ID, add_food.`Item_Type` AS add_food_Item_Type, add_food.`Item_Name` AS add_food_Item_Name, add_food.`Price` AS add_food_Price FROM `add_food` add_food";
   Show();
    }//GEN-LAST:event_lblAddFoodMouseClicked

    private void lblBreakageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBreakageMouseClicked
        m_report_source = "rptBreakage.jrxml";
        m_sql_stmt = "SELECT breakage.`ID` AS breakage_ID, breakage.`Item_Type` AS breakage_Item_Type, breakage.`Item_Name` AS breakage_Item_Name, breakage.`Price` AS breakage_Price, breakage.`Brk_Quantity` AS breakage_Brk_Quantity, breakage.`Brk_Price` AS breakage_Brk_Price FROM `breakage` breakage";
   Show();
    }//GEN-LAST:event_lblBreakageMouseClicked

    private void lblAddMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMaterialMouseClicked
        m_report_source = "Material.jrxml";
        m_sql_stmt = "SELECT add_material.`ID` AS add_material_ID, add_material.`Item_Type` AS add_material_Item_Type, add_material.`Item_Name` AS add_material_Item_Name, add_material.`Quantity` AS add_material_Quantity, add_material.`Price` AS add_material_Price FROM `add_material` add_material";
   Show();
    }//GEN-LAST:event_lblAddMaterialMouseClicked

    private void lblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseClicked
        m_report_source = "rptCust.jrxml";
        m_sql_stmt = "SELECT    customer.`Id` AS customer_Id, customer.`Name` AS customer_Name, customer.`Address` AS customer_Address,  customer.`MobNo` AS customer_MobNo FROM `customer` customer";
   Show();
    }//GEN-LAST:event_lblCustomerMouseClicked

    private void lblFoodBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoodBillMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFoodBillMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAddFood;
    private javax.swing.JLabel lblAddMaterial;
    private javax.swing.JLabel lblBreakage;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblFoodBill;
    // End of variables declaration//GEN-END:variables
}
